site_name: 电子技术文档 - 信念D力量
site_description: 该网站为电子技术文档。
site_author: 信念D力量
site_url: https://zsf90.github.io/
copyright: 'Copyright © 2021 <a href="https://zsf90.github.io" target="_blank" title="zsf90">信念D力量</a>'

nav:
  - 首页: index.md
  - "运放": '运放.md'
  - "GD32": 'gd32.md'
  - "STC": 'stc.md'
  - "STM32": 'stm32.md'
  - "Altium Designer": 'altium_designer.md'
  - "传感器": '传感器列表.md'
  - "元器件": '电子器件列表.md'
  - "EC11旋转编码器": 'ec11-encoder.md'

  - 关于:
    - 'About': 'about.md'

theme:
  name: readthedocs # mkdocs # readthedocs
  locale: zh_CN
  sticky_navigation: false # 侧栏是否一起滚动
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

extra_css:
  - css/zsf90.css

markdown_extensions:
  - admonition

