site_name: 编程文档 - 信念D力量
site_description: 该网站为我的编程文档。
site_author: 信念D力量
site_url: https://zsf90.github.io/
copyright: 'Copyright © 2021 <a href="https://zsf90.github.io" target="_blank" title="zsf90">信念D力量</a>'

nav:
  - 首页: index.md
  - 语言:
    - "C": 'c.md'
    - "C++": 'cplusplus.md'
    - "Rust": 'rust.md'
    - "Python": 'python.md'
    - "HTML": 'html.md'
    - "CSS": 'css.md'
    - "JavsScript": 'javascript.md'
    - 'CSharp': 'csharp.md'
    - 'WinForm': 'winform.md'

  - 关于:
    - 'About': 'about.md'

theme:
  name: readthedocs # mkdocs # readthedocs
  locale: zh_CN
  sticky_navigation: false # 侧栏是否一起滚动
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

extra_css:
  - css/zsf90.css

markdown_extensions:
  - admonition

