site_name: FreeRTOS 学习笔记 - 信念D力量
site_description: FreeRTOS 笔记站点
site_author: 信念D力量
site_url: https://zsf90.github.io/
copyright: 'Copyright © 2021 <a href="https://zsf90.github.io" target="_blank" title="zsf90">信念D力量</a>'

nav:
  - 首页: index.md
  - 基础:
    - "任务": 'task.md'
    - "事件": 'event_group.md'
    - "信号量": semaphore.md
    - "定时器": timer.md

  - 关于:
    - 'About': 'about.md'

theme:
  name: readthedocs # mkdocs # readthedocs
  locale: zh_CN
  sticky_navigation: false # 侧栏是否一起滚动
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

extra_css:
  - css/zsf90.css

markdown_extensions:
  - admonition