site_name: Rust 编程文档 - 信念D力量
site_description: 这是我的 Rust 编程文档。
site_author: 信念D力量
site_url: https://www.zsf90.com
copyright: 'Copyright © 2021 <a href="https://zsf90.github.io" target="_blank" title="zsf90">信念D力量</a>'

nav:
  - 首页: index.md
  - 基础:
    - 数据类型: data-type.md
    - 结构体: struct.md
    - Trait: Trait.md
  - std标准库:
    - ops 模块: std-ops.md
  - 库列表: lib-list.md
  - 关于:
    - 'About': 'about.md'
    - 'License': 'license.md'

theme:
  name: readthedocs # readthedocs
  locale: zh_CN
  sticky_navigation: false # 侧栏是否一起滚动
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

extra_css:
  - css/zsf90.css

markdown_extensions:
  - admonition

